name: Test actions

on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - name: Init
        run:  |
          ./ci/scrip1.sh
  job2:
    runs-on: ubuntu-20.04
    steps:
      - name: Init2
        run: |
          ./ci/script2.sh