name: Test actions

on:
  push:
    branches:
      - main
env:
  ENV1: environment

jobs:
  job1:
    runs-on: ubuntu-20.04
    outputs:
      job-status: ${{ steps.step2.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref:  ${{ github.event.pull_request.head.sha }}
      - name: Init
        id: step2
        run:  |
          ./.ci/scrip1.sh &&
          env &&
          echo "----- ${ENV3}" &&
          echo "-----1 $ENV3" &&
          echo "-----2 ${{ env.ENV3 }}" &&
          echo "::set-output name=status::${ENV3}" 
  job2:
    runs-on: ubuntu-20.04
    needs: job1
    if: needs.job1.outputs.job-status == 'in1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref:  ${{ github.event.pull_request.head.sha }}
      - name: Init2
        run: |
          ./.ci/script2.sh &&
          echo "${{ env.ENV1 }}" 