name: Test actions

on:
  push:
    branches:
      - main
env:
  ENV1: environment

jobs:
  job1:
    runs-on: ubuntu-20.04
    outputs:
      job-status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref:  ${{ github.event.pull_request.head.sha }}
      - name: Init
        run:  |
          ./.ci/scrip1.sh &&
          echo "${{ env.ENV1 }}" 
  job2:
    runs-on: ubuntu-20.04
    needs: job1
    if: needs.job1.outputs.job-status == 'Success'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref:  ${{ github.event.pull_request.head.sha }}
      - name: Init2
        run: |
          ./.ci/script2.sh &&
          echo "${{ env.ENV1 }}" 